scan_timeout = 10
add_newline = true

format = '$directory$git_branch$character'
right_format = '$python$java'

[character]
success_symbol = ' [❯](bold white)'
error_symbol = ' [✗](bold red)'
vimcmd_symbol = ' [❮](bold green)'

[directory]
format = '[$read_only]($read_only_style)[$path]($style)'
home_symbol = '~'
style = 'bold blue'
truncation_length = 2
truncation_symbol = '…/'

[git_branch]
format = ' git:\([$branch](red)\)'

[java]
format = '[${symbol}(${version} )]($style)'
detect_extensions = ['java', 'class', 'gradle', 'jar', 'cljs', 'cljc']
style = 'red dimmed'

[profiles]
transient = "$character"
# add_newline = false

[python]
format = '[${symbol}${pyenv_prefix}(${version} )(\($virtualenv\) )]($style)'
style =	'yellow bold'
